#!/usr/bin/env bash
#
# Local Supabase env provisioning for worktrees.
#
# Writes .env.local pointing to the local Supabase instance (started via
# `supabase start` in the main checkout). The local Supabase has:
#   - Kong gateway (auth + REST): http://localhost:54321
#   - Postgres:                   localhost:54322
#   - JWT secret:                 super-secret-jwt-token-with-at-least-32-characters-long
#   - Anon key:                   (standard Supabase demo anon key)
#   - Service role key:           (standard Supabase demo service key)
#
# The local Supabase already has migrations applied and a seeded test user,
# so no seeding is needed.
#
# Usage (called by wta):
#   wt-supabase-env <worktree-dir> <app-port>
#
# This script is safe to run multiple times — it won't overwrite an
# existing .env.local unless --force is passed.

set -euo pipefail

DEST="${1:?missing worktree dir}"
APP_PORT="${2:?missing app port}"
FORCE="${3:-}"

ENV_LOCAL="$DEST/.env.local"

if [ -f "$ENV_LOCAL" ] && [ "$FORCE" != "--force" ]; then
  echo "→ .env.local already exists (use --force to overwrite)"
  exit 0
fi

# Standard Supabase local demo keys (from `supabase start`)
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long"

# Local Supabase connection strings
DB_HOST="localhost"
DB_PORT="54322"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_NAME="postgres"

# Determine the host the browser will use to access this worktree.
# The handler dashboard links to the LAN IP, so ORIGIN must match.
# If accessed via localhost (e.g. SSH tunnel), use localhost.
HOST="${PUBLIC_HOST:-}"
if [ -z "$HOST" ]; then
  # Auto-detect LAN IP (prefer 192.168.x.x)
  HOST=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep '^192\.168\.' | head -1)
  [ -z "$HOST" ] && HOST=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep '^10\.' | head -1)
  [ -z "$HOST" ] && HOST="localhost"
fi

cat > "$ENV_LOCAL" << EOF
# Auto-generated by wt-supabase-env — local Supabase for dev worktrees.
# DO NOT COMMIT. This file overrides .env for local development.

# Local Supabase (started via \`supabase start\` in the main checkout)
DATABASE_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
DIRECT_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
PUBLIC_SUPABASE_URL="http://localhost:54321"
PUBLIC_SUPABASE_ANON_KEY="$ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY="$SERVICE_KEY"
JWT_SECRET="$JWT_SECRET"

# ORIGIN must match the URL the browser uses (LAN IP for remote access)
ORIGIN="http://$HOST:$APP_PORT"

# Local mode — flags local-dev behavior for the app.
LOCAL_MODE="true"
EOF

echo "→ wrote $ENV_LOCAL (Supabase: localhost:54321, DB: $DB_HOST:$DB_PORT, ORIGIN: http://$HOST:$APP_PORT)"